title: raravel
subtitle: 'sadfasdf'
description: Description
keywords: null
author: raravel
language: en
timezone: ''
url: 'https://raravel.github.io/'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: docs
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
lazyload:
  enable: false
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
plugins:
  - hexo-server
theme: fluid
sitemap:
  path: sitemap.xml
nofollow:
  enable: true
feed:
  type: rss2
  path: feed.xml
  limit: 20
robotstxt:
  useragent: '*'
  allow:
    - '*'
  sitemap: /sitemap.xml
