name: build CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm ci
    - run: rm -rf docs
    - run: npm run build
    - run: rm -rf package-lock.json node_modules docs/images
    #- run: '[[ -d "source/images" ]] && cp -r source/images docs/images'
    - run: git submodule deinit .
    - run: git config --global --add safe.directory /github/workspace
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'build commit'
        force-add: 'true'
        name: 'Github Actions'
        email: 'git.page-story@gmail.com'
        file-path: |
          meta-data.json
          docs/**
